#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AppAndroid.Resource", IsApplication=true)]

namespace AppAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040005
			public const int btnLogin = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int btnRegistro = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int etPassword = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int etUserName = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int lvLista = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int tvSubtitle = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int tvTitle = 2130968576;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int DetalleLayout = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ItemLayout = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int LandingPageLayout = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int LoginLayout = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Main = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int RegistroLayout = 2130837509;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
